# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_remove_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='doc',
        ),
        migrations.AddField(
            model_name='task',
            name='xml',
            field=models.FileField(default=b'Xml/None/No-xml.xml', upload_to=b'Xml/'),
        ),
    ]
